apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.7.2
    helm:
      values: |
        alertmanager:
          enabled: false
        grafana:
          adminPassword: "admin"
          service:
            type: ClusterIP
        prometheus:
          prometheusSpec:
            retention: 2d
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 300m
        prometheusOperator:
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
