apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: springcommunity/spring-petclinic-rest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9966
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-credentials
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-credentials
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: default
spec:
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 9966
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: petclinic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic
                port:
                  number: 80
